ALTER TABLE comarcas ADD COLUMN as_built_homologacao_legada_sem_justificativa boolean NOT NULL DEFAULT false;

CREATE TABLE historico_homologacao_as_built (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comarca_id bigint NOT NULL REFERENCES comarcas(id),
    status varchar(40) NOT NULL,
    justificativa text,
    responsavel varchar(160) NOT NULL,
    registrado_em timestamp without time zone NOT NULL
);

CREATE INDEX idx_homologacao_as_built_comarca ON historico_homologacao_as_built (comarca_id, id);
